### ISSUE TITLE
default 브랜치에는 예외가 발생하지 않는 코드만 존재하게 한다.

### ISSUE THREAD

**Issue by nayonsoso** [solid-connection/solid-connect-server#111]
## 어떤 버그인가요

> 문제가 되는 부분에 대해 설명해주세요

별도의 배경지식 없이, 이 레포를 클론 후 바로 실행할 신입 개발자는 아래 상황을 마주한다🤧

![image](https://github.com/user-attachments/assets/8102b429-4c4a-4ef4-b8f0-5deacea5ce21)
![image](https://github.com/user-attachments/assets/d8534495-c630-4c25-a00f-b5d77e969855)

따라서, default 브랜치에는 문제가 없는 코드만 올라오도록 할 필요가 있다.

## TODO
- [x] 현재 브랜치에서 발생하는 문제가 터지지 않게 수정한다.
  - [x] 로직으로 인한 문제를 해결한다.
  - [x] config 파일로 인한 문제를 해결한다.
- [ ] CI 를 만들어, "defualt 에는 문제가 없는 코드만 올라오도록" 하는 것을 시스템으로 만든다.
